"""schema initial

Revision ID: b893b876a645
Revises: 
Create Date: 2026-09-22 11:36:07.320344

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b893b876a645'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bench_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bench_type'))
    )
    op.create_table('diplome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diplome')),
    sa.UniqueConstraint('libelle', name=op.f('uq_diplome_libelle'))
    )
    op.create_table('famille_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_famille_article')),
    sa.UniqueConstraint('libelle', name=op.f('uq_famille_article_libelle'))
    )
    op.create_table('maladie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maladie')),
    sa.UniqueConstraint('libelle', name=op.f('uq_maladie_libelle'))
    )
    op.create_table('parametre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_site', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('telephone_1', sa.String(length=20), nullable=False),
    sa.Column('telephone_2', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('texte_aide', sa.Text(), nullable=False),
    sa.Column('montant_minimum_placement', sa.BigInteger(), nullable=False),
    sa.Column('montant_minimum_course', sa.BigInteger(), nullable=False),
    sa.Column('commission_course', sa.BigInteger(), nullable=False),
    sa.Column('conditions_course', sa.Text(), nullable=False),
    sa.Column('description_section_1', sa.Text(), nullable=False),
    sa.Column('description_section_2', sa.Text(), nullable=False),
    sa.Column('description_section_3', sa.Text(), nullable=False),
    sa.Column('description_section_4', sa.Text(), nullable=False),
    sa.Column('description_section_5', sa.Text(), nullable=False),
    sa.Column('description_section_6', sa.Text(), nullable=False),
    sa.Column('description_section_7', sa.Text(), nullable=False),
    sa.Column('module_epargne_actif', sa.Boolean(), nullable=False),
    sa.Column('module_sante_actif', sa.Boolean(), nullable=False),
    sa.Column('compteur_membre', sa.Integer(), nullable=False),
    sa.Column('compteur_reference', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametre'))
    )
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('groupe', sa.SmallInteger(), nullable=False),
    sa.Column('prix_distributeur', sa.BigInteger(), nullable=False),
    sa.Column('prix_non_distributeur', sa.BigInteger(), nullable=False),
    sa.Column('prix_public', sa.BigInteger(), nullable=False),
    sa.Column('quantite_stock', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produit'))
    )
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produit_groupe'), ['groupe'], unique=False)

    op.create_table('produit_prospective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produit_prospective')),
    sa.UniqueConstraint('nom', name=op.f('uq_produit_prospective_nom'))
    )
    op.create_table('secteur_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secteur_activite'))
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion'))
    )
    op.create_table('tentative_connexion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=120), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tentative_connexion'))
    )
    with op.batch_alter_table('tentative_connexion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tentative_connexion_cle'), ['cle'], unique=False)
        batch_op.create_index(batch_op.f('ix_tentative_connexion_date_heure'), ['date_heure'], unique=False)

    op.create_table('ville',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ville')),
    sa.UniqueConstraint('nom', name=op.f('uq_ville_nom'))
    )
    op.create_table('bench_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['bench_type.id'], name=op.f('fk_bench_operation_type_id_bench_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bench_operation'))
    )
    op.create_table('domaine_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secteur_id', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur_activite.id'], name=op.f('fk_domaine_activite_secteur_id_secteur_activite')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domaine_activite'))
    )
    op.create_table('maladie_produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maladie_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('posologie', sa.Text(), nullable=False),
    sa.Column('ordre', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['maladie_id'], ['maladie.id'], name=op.f('fk_maladie_produit_maladie_id_maladie'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], name=op.f('fk_maladie_produit_produit_id_produit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maladie_produit'))
    )
    op.create_table('quartier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ville_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['ville_id'], ['ville.id'], name=op.f('fk_quartier_ville_id_ville')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quartier'))
    )
    op.create_table('membre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_compte', sa.SmallInteger(), nullable=False),
    sa.Column('categorie', sa.SmallInteger(), nullable=False),
    sa.Column('code_membre', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('pseudonyme', sa.String(length=50), nullable=False),
    sa.Column('sexe', sa.SmallInteger(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('identifiant', sa.String(length=50), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('droit_attribution', sa.Boolean(), nullable=False),
    sa.Column('droit_caisse', sa.Boolean(), nullable=False),
    sa.Column('droit_activation', sa.Boolean(), nullable=False),
    sa.Column('numero_piece_identite', sa.String(length=50), nullable=False),
    sa.Column('employeur', sa.String(length=120), nullable=False),
    sa.Column('situation_matrimoniale', sa.SmallInteger(), nullable=True),
    sa.Column('nombre_enfants', sa.SmallInteger(), nullable=False),
    sa.Column('forme_juridique', sa.SmallInteger(), nullable=True),
    sa.Column('type_partenaire', sa.SmallInteger(), nullable=True),
    sa.Column('domaine_activite_id', sa.Integer(), nullable=True),
    sa.Column('date_limite_master', sa.Date(), nullable=True),
    sa.Column('point_caisse_actif', sa.Boolean(), nullable=False),
    sa.Column('solde_point_caisse', sa.BigInteger(), nullable=False),
    sa.Column('date_dernier_pointage', sa.DateTime(), nullable=True),
    sa.Column('code_pointage_hash', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('derniere_activite', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domaine_activite_id'], ['domaine_activite.id'], name=op.f('fk_membre_domaine_activite_id_domaine_activite')),
    sa.ForeignKeyConstraint(['ville_id'], ['ville.id'], name=op.f('fk_membre_ville_id_ville')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membre')),
    sa.UniqueConstraint('identifiant', name=op.f('uq_membre_identifiant'))
    )
    with op.batch_alter_table('membre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membre_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_membre_telephone'), ['telephone'], unique=False)

    op.create_table('annonce_emploi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('type_annonce', sa.SmallInteger(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('secteur_id', sa.Integer(), nullable=True),
    sa.Column('domaine_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('sexe', sa.SmallInteger(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('diplomes', sa.Text(), nullable=False),
    sa.Column('savoir_faire', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('experience_2', sa.Text(), nullable=False),
    sa.Column('competences', sa.Text(), nullable=False),
    sa.Column('poste_a_pourvoir', sa.Text(), nullable=False),
    sa.Column('autres_informations', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('cv', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_annonce_emploi_auteur_id_membre')),
    sa.ForeignKeyConstraint(['domaine_id'], ['domaine_activite.id'], name=op.f('fk_annonce_emploi_domaine_id_domaine_activite')),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur_activite.id'], name=op.f('fk_annonce_emploi_secteur_id_secteur_activite')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annonce_emploi'))
    )
    with op.batch_alter_table('annonce_emploi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annonce_emploi_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_annonce_emploi_type_annonce'), ['type_annonce'], unique=False)

    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('famille_id', sa.Integer(), nullable=True),
    sa.Column('offre_ou_recherche', sa.SmallInteger(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('prix', sa.BigInteger(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('neuf_ou_occasion', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_article_auteur_id_membre')),
    sa.ForeignKeyConstraint(['famille_id'], ['famille_article.id'], name=op.f('fk_article_famille_id_famille_article')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_offre_ou_recherche'), ['offre_ou_recherche'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_reference'), ['reference'], unique=False)

    op.create_table('article_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boutique_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('marque', sa.String(length=120), nullable=False),
    sa.Column('prix', sa.BigInteger(), nullable=False),
    sa.Column('disponible', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['membre.id'], name=op.f('fk_article_course_boutique_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_course'))
    )
    with op.batch_alter_table('article_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_course_boutique_id'), ['boutique_id'], unique=False)

    op.create_table('banque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('sigle', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('telephones', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('site_web', sa.String(length=200), nullable=False),
    sa.Column('nom_contact', sa.String(length=100), nullable=False),
    sa.Column('telephone_contact', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_banque_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banque'))
    )
    op.create_table('business_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('type_activite', sa.Text(), nullable=False),
    sa.Column('description_projet', sa.Text(), nullable=False),
    sa.Column('moyens_actuels', sa.Text(), nullable=False),
    sa.Column('ressources_disponibles', sa.Text(), nullable=False),
    sa.Column('possessions', sa.Text(), nullable=False),
    sa.Column('organisation_actuelle', sa.Text(), nullable=False),
    sa.Column('organisation_souhaitee', sa.Text(), nullable=False),
    sa.Column('detail_besoin', sa.Text(), nullable=False),
    sa.Column('apport_actuel', sa.Text(), nullable=False),
    sa.Column('ambition', sa.Text(), nullable=False),
    sa.Column('strategie_resultats', sa.Text(), nullable=False),
    sa.Column('valeur_ajoutee', sa.Text(), nullable=False),
    sa.Column('prevision_ca_benefice', sa.Text(), nullable=False),
    sa.Column('processus_activite', sa.Text(), nullable=False),
    sa.Column('estimation_charges', sa.Text(), nullable=False),
    sa.Column('composantes_ca', sa.Text(), nullable=False),
    sa.Column('repartition_ca', sa.Text(), nullable=False),
    sa.Column('elements_environnementaux', sa.Text(), nullable=False),
    sa.Column('strategie_attaque', sa.Text(), nullable=False),
    sa.Column('devis_chiffre_besoin', sa.Text(), nullable=False),
    sa.Column('apport_prevu', sa.Text(), nullable=False),
    sa.Column('niveau_realisation', sa.SmallInteger(), nullable=False),
    sa.Column('difficultes_realisation', sa.Text(), nullable=False),
    sa.Column('planning_execution', sa.Text(), nullable=False),
    sa.Column('difficultes_futures', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_business_plan_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_plan')),
    sa.UniqueConstraint('membre_id', name=op.f('uq_business_plan_membre_id'))
    )
    op.create_table('conseil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('sujet_id', sa.Integer(), nullable=True),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('confidentialite', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_reponses', sa.Integer(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_conseil_auteur_id_membre')),
    sa.ForeignKeyConstraint(['sujet_id'], ['conseil.id'], name=op.f('fk_conseil_sujet_id_conseil')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conseil'))
    )
    with op.batch_alter_table('conseil', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conseil_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_conseil_sujet_id'), ['sujet_id'], unique=False)

    op.create_table('conseil_finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrique', sa.SmallInteger(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('sujet_id', sa.Integer(), nullable=True),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('auteur_sujet_id', sa.Integer(), nullable=True),
    sa.Column('confidentialite', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_reponses', sa.Integer(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_conseil_finance_auteur_id_membre')),
    sa.ForeignKeyConstraint(['auteur_sujet_id'], ['membre.id'], name=op.f('fk_conseil_finance_auteur_sujet_id_membre')),
    sa.ForeignKeyConstraint(['sujet_id'], ['conseil_finance.id'], name=op.f('fk_conseil_finance_sujet_id_conseil_finance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conseil_finance'))
    )
    with op.batch_alter_table('conseil_finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conseil_finance_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_conseil_finance_rubrique'), ['rubrique'], unique=False)
        batch_op.create_index(batch_op.f('ix_conseil_finance_sujet_id'), ['sujet_id'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('reponse', sa.Text(), nullable=False),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_contact_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_table('contentieux_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_dossier', sa.DateTime(), nullable=False),
    sa.Column('dette_compromise', sa.BigInteger(), nullable=False),
    sa.Column('dette_compromise_detail', sa.Text(), nullable=False),
    sa.Column('revenus_journaliers', sa.BigInteger(), nullable=False),
    sa.Column('revenus_journaliers_detail', sa.Text(), nullable=False),
    sa.Column('revenus_hebdomadaires', sa.BigInteger(), nullable=False),
    sa.Column('revenus_hebdomadaires_detail', sa.Text(), nullable=False),
    sa.Column('revenus_mensuels', sa.BigInteger(), nullable=False),
    sa.Column('revenus_mensuels_detail', sa.Text(), nullable=False),
    sa.Column('charges_fixes', sa.BigInteger(), nullable=False),
    sa.Column('charges_fixes_detail', sa.Text(), nullable=False),
    sa.Column('charges_variables', sa.BigInteger(), nullable=False),
    sa.Column('charges_variables_detail', sa.Text(), nullable=False),
    sa.Column('activites_en_cours', sa.Text(), nullable=False),
    sa.Column('entrees_activite_en_cours', sa.BigInteger(), nullable=False),
    sa.Column('entrees_activite_en_cours_detail', sa.Text(), nullable=False),
    sa.Column('activite_previsionnelle', sa.Text(), nullable=False),
    sa.Column('entrees_previsionnelles', sa.BigInteger(), nullable=False),
    sa.Column('entrees_previsionnelles_detail', sa.Text(), nullable=False),
    sa.Column('entrees_totales', sa.BigInteger(), nullable=False),
    sa.Column('entrees_totales_detail', sa.Text(), nullable=False),
    sa.Column('echeance_actuelle', sa.Text(), nullable=False),
    sa.Column('echeance_supportable', sa.BigInteger(), nullable=False),
    sa.Column('echeance_supportable_detail', sa.Text(), nullable=False),
    sa.Column('elements_favorables', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_contentieux_credit_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contentieux_credit'))
    )
    with op.batch_alter_table('contentieux_credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contentieux_credit_reference'), ['reference'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('boutique_id', sa.Integer(), nullable=True),
    sa.Column('lieu_achat', sa.Text(), nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=True),
    sa.Column('date_livraison', sa.DateTime(), nullable=True),
    sa.Column('lieu_livraison', sa.Text(), nullable=False),
    sa.Column('montant_achats', sa.BigInteger(), nullable=False),
    sa.Column('frais_service', sa.BigInteger(), nullable=False),
    sa.Column('mode_paiement', sa.SmallInteger(), nullable=False),
    sa.Column('paye', sa.SmallInteger(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat_course', sa.SmallInteger(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['membre.id'], name=op.f('fk_course_boutique_id_membre')),
    sa.ForeignKeyConstraint(['client_id'], ['membre.id'], name=op.f('fk_course_client_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_reference'), ['reference'], unique=False)

    op.create_table('demande_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_demande', sa.Date(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('duree_mois', sa.SmallInteger(), nullable=False),
    sa.Column('niveau_realisation', sa.Float(), nullable=False),
    sa.Column('garantie', sa.Text(), nullable=False),
    sa.Column('delai_reponse_jours', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('devis_global', sa.Text(), nullable=False),
    sa.Column('apport_propre', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_demande_credit_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demande_credit'))
    )
    with op.batch_alter_table('demande_credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demande_credit_reference'), ['reference'], unique=False)

    op.create_table('dialogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=True),
    sa.Column('type_dialogue', sa.SmallInteger(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('date_message', sa.DateTime(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_dialogue_auteur_id_membre')),
    sa.ForeignKeyConstraint(['destinataire_id'], ['membre.id'], name=op.f('fk_dialogue_destinataire_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialogue'))
    )
    with op.batch_alter_table('dialogue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialogue_type_dialogue'), ['type_dialogue'], unique=False)

    op.create_table('dossier_accompagnement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_dossier', sa.SmallInteger(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('reponses', sa.JSON(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_dossier_accompagnement_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_accompagnement'))
    )
    with op.batch_alter_table('dossier_accompagnement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_accompagnement_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_dossier_accompagnement_type_dossier'), ['type_dossier'], unique=False)

    op.create_table('entreprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('secteur_id', sa.Integer(), nullable=True),
    sa.Column('domaine_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('forme_juridique', sa.SmallInteger(), nullable=False),
    sa.Column('capital_social', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=False),
    sa.Column('gerant', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('site_web', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domaine_id'], ['domaine_activite.id'], name=op.f('fk_entreprise_domaine_id_domaine_activite')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_entreprise_membre_id_membre')),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur_activite.id'], name=op.f('fk_entreprise_secteur_id_secteur_activite')),
    sa.ForeignKeyConstraint(['ville_id'], ['ville.id'], name=op.f('fk_entreprise_ville_id_ville')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entreprise'))
    )
    with op.batch_alter_table('entreprise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entreprise_reference'), ['reference'], unique=False)

    op.create_table('fond_de_soutien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_souscription', sa.Date(), nullable=True),
    sa.Column('type_fond', sa.SmallInteger(), nullable=False),
    sa.Column('rapporteur_id', sa.Integer(), nullable=True),
    sa.Column('rapporteur_nom', sa.String(length=120), nullable=False),
    sa.Column('souscripteur_id', sa.Integer(), nullable=True),
    sa.Column('souscripteur_nom', sa.String(length=120), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('duree_mois', sa.SmallInteger(), nullable=False),
    sa.Column('mode_paiement', sa.SmallInteger(), nullable=False),
    sa.Column('confirme', sa.SmallInteger(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_fond_de_soutien_membre_id_membre')),
    sa.ForeignKeyConstraint(['rapporteur_id'], ['membre.id'], name=op.f('fk_fond_de_soutien_rapporteur_id_membre')),
    sa.ForeignKeyConstraint(['souscripteur_id'], ['membre.id'], name=op.f('fk_fond_de_soutien_souscripteur_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fond_de_soutien'))
    )
    with op.batch_alter_table('fond_de_soutien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fond_de_soutien_reference'), ['reference'], unique=False)

    op.create_table('groupe_likelemba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('montant_cotisation', sa.BigInteger(), nullable=False),
    sa.Column('periodicite', sa.SmallInteger(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('compteur_entrees', sa.Integer(), nullable=False),
    sa.Column('compteur_paiements', sa.Integer(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['membre.id'], name=op.f('fk_groupe_likelemba_responsable_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groupe_likelemba'))
    )
    with op.batch_alter_table('groupe_likelemba', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groupe_likelemba_code'), ['code'], unique=False)

    op.create_table('immobilier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('offre_ou_recherche', sa.SmallInteger(), nullable=False),
    sa.Column('type_transaction', sa.SmallInteger(), nullable=False),
    sa.Column('type_bien', sa.SmallInteger(), nullable=False),
    sa.Column('quartier_id', sa.Integer(), nullable=True),
    sa.Column('localisation', sa.Text(), nullable=False),
    sa.Column('surface_m2', sa.Integer(), nullable=False),
    sa.Column('nombre_pieces', sa.SmallInteger(), nullable=False),
    sa.Column('nombre_chambres', sa.SmallInteger(), nullable=False),
    sa.Column('situation', sa.SmallInteger(), nullable=False),
    sa.Column('prix', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_immobilier_auteur_id_membre')),
    sa.ForeignKeyConstraint(['quartier_id'], ['quartier.id'], name=op.f('fk_immobilier_quartier_id_quartier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_immobilier'))
    )
    with op.batch_alter_table('immobilier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immobilier_offre_ou_recherche'), ['offre_ou_recherche'], unique=False)
        batch_op.create_index(batch_op.f('ix_immobilier_reference'), ['reference'], unique=False)

    op.create_table('marche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('numero_appel_offre', sa.String(length=120), nullable=False),
    sa.Column('type_marche', sa.SmallInteger(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('dossier_a_fournir', sa.Text(), nullable=False),
    sa.Column('lieu_depot', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('maitre_ouvrage', sa.Text(), nullable=False),
    sa.Column('publie_par', sa.Text(), nullable=False),
    sa.Column('beneficiaire', sa.Text(), nullable=False),
    sa.Column('document', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_marche_auteur_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marche'))
    )
    with op.batch_alter_table('marche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marche_reference'), ['reference'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('de_la_frangine', sa.Boolean(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('date_message', sa.DateTime(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_message_auteur_id_membre')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_message_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_membre_id'), ['membre_id'], unique=False)

    op.create_table('paiement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('type_objet', sa.SmallInteger(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.SmallInteger(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('confirme_par_id', sa.Integer(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirme_par_id'], ['membre.id'], name=op.f('fk_paiement_confirme_par_id_membre')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_paiement_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paiement'))
    )
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paiement_etat'), ['etat'], unique=False)
        batch_op.create_index(batch_op.f('ix_paiement_membre_id'), ['membre_id'], unique=False)

    op.create_table('partenariat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recherche', sa.Text(), nullable=False),
    sa.Column('objectif', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_partenariat_auteur_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partenariat'))
    )
    with op.batch_alter_table('partenariat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partenariat_reference'), ['reference'], unique=False)

    op.create_table('placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('type_placement', sa.SmallInteger(), nullable=False),
    sa.Column('date_placement', sa.DateTime(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('duree_mois', sa.SmallInteger(), nullable=False),
    sa.Column('taux', sa.Float(), nullable=False),
    sa.Column('banque', sa.String(length=120), nullable=False),
    sa.Column('secteur_activite', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_placement_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement'))
    )
    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_reference'), ['reference'], unique=False)

    op.create_table('point_caisse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=True),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.SmallInteger(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('solde_apres', sa.BigInteger(), nullable=False),
    sa.Column('type_caisse', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_point_caisse_membre_id_membre')),
    sa.ForeignKeyConstraint(['operateur_id'], ['membre.id'], name=op.f('fk_point_caisse_operateur_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_caisse'))
    )
    with op.batch_alter_table('point_caisse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_caisse_date_heure'), ['date_heure'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_caisse_membre_id'), ['membre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_caisse_reference'), ['reference'], unique=False)

    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('responsable', sa.Text(), nullable=False),
    sa.Column('promoteur', sa.Text(), nullable=False),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('objectif', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('duree_mois', sa.SmallInteger(), nullable=False),
    sa.Column('date_lancement', sa.Date(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_projet_auteur_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projet'))
    )
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projet_reference'), ['reference'], unique=False)

    op.create_table('reinitialisation_mot_de_passe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('jeton_hash', sa.String(length=64), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('date_utilisation', sa.DateTime(), nullable=True),
    sa.Column('traitee_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_reinitialisation_mot_de_passe_membre_id_membre'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traitee_par_id'], ['membre.id'], name=op.f('fk_reinitialisation_mot_de_passe_traitee_par_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reinitialisation_mot_de_passe')),
    sa.UniqueConstraint('jeton_hash', name=op.f('uq_reinitialisation_mot_de_passe_jeton_hash'))
    )
    op.create_table('reussite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('secteur_id', sa.Integer(), nullable=True),
    sa.Column('situation_avant', sa.Text(), nullable=False),
    sa.Column('vision', sa.Text(), nullable=False),
    sa.Column('projet', sa.Text(), nullable=False),
    sa.Column('fond_demarrage', sa.BigInteger(), nullable=False),
    sa.Column('besoin_reel_demarrage', sa.BigInteger(), nullable=False),
    sa.Column('strategie', sa.Text(), nullable=False),
    sa.Column('difficultes', sa.Text(), nullable=False),
    sa.Column('deploiement_efforts', sa.Text(), nullable=False),
    sa.Column('succes', sa.Text(), nullable=False),
    sa.Column('conseil', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_reussite_membre_id_membre')),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur_activite.id'], name=op.f('fk_reussite_secteur_id_secteur_activite')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reussite')),
    sa.UniqueConstraint('membre_id', name=op.f('uq_reussite_membre_id'))
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('jeton_hash', sa.String(length=64), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_session_membre_id_membre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('jeton_hash', name=op.f('uq_session_jeton_hash'))
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_membre_id'), ['membre_id'], unique=False)

    op.create_table('soungangai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('activite_actuelle', sa.Text(), nullable=False),
    sa.Column('savoir_faire', sa.Text(), nullable=False),
    sa.Column('activite_quotidienne', sa.Text(), nullable=False),
    sa.Column('secret_a_partager', sa.Text(), nullable=False),
    sa.Column('origine_idee', sa.Text(), nullable=False),
    sa.Column('idee_vue_chez_autrui', sa.SmallInteger(), nullable=False),
    sa.Column('participation_idee_tierce', sa.Text(), nullable=False),
    sa.Column('est_sociable', sa.SmallInteger(), nullable=False),
    sa.Column('interet_pour_autrui', sa.SmallInteger(), nullable=False),
    sa.Column('a_deja_fait_commerce', sa.SmallInteger(), nullable=False),
    sa.Column('se_fait_des_amis', sa.SmallInteger(), nullable=False),
    sa.Column('garde_ses_relations', sa.SmallInteger(), nullable=False),
    sa.Column('percu_comme_ouvert', sa.SmallInteger(), nullable=False),
    sa.Column('perception_par_autrui', sa.Text(), nullable=False),
    sa.Column('est_meneur', sa.SmallInteger(), nullable=False),
    sa.Column('prefere_entourage', sa.SmallInteger(), nullable=False),
    sa.Column('a_des_amis_proches', sa.SmallInteger(), nullable=False),
    sa.Column('entourage_valorise_activite', sa.SmallInteger(), nullable=False),
    sa.Column('entourage_proche', sa.Text(), nullable=False),
    sa.Column('personnes_consideration', sa.Text(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('pourcentage_implication', sa.SmallInteger(), nullable=False),
    sa.Column('moyens_disponibles', sa.Text(), nullable=False),
    sa.Column('soutien_conjoint', sa.SmallInteger(), nullable=False),
    sa.Column('origine_soutien', sa.Text(), nullable=False),
    sa.Column('confronte_aux_faits', sa.SmallInteger(), nullable=False),
    sa.Column('notes_membre', sa.Text(), nullable=False),
    sa.Column('notes_conseillere', sa.Text(), nullable=False),
    sa.Column('etat_fiche', sa.SmallInteger(), nullable=False),
    sa.Column('cloturee', sa.SmallInteger(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('diagnostic', sa.JSON(), nullable=True),
    sa.Column('date_diagnostic', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_soungangai_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soungangai')),
    sa.UniqueConstraint('membre_id', name=op.f('uq_soungangai_membre_id'))
    )
    op.create_table('souscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('objectifs', sa.Text(), nullable=False),
    sa.Column('mon_histoire', sa.Text(), nullable=False),
    sa.Column('disponibilite_hebdo', sa.SmallInteger(), nullable=False),
    sa.Column('formations', sa.JSON(), nullable=False),
    sa.Column('nombre_rdv', sa.SmallInteger(), nullable=False),
    sa.Column('filleuls', sa.JSON(), nullable=False),
    sa.Column('mode_souscription', sa.SmallInteger(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('date_limite_complement', sa.Date(), nullable=True),
    sa.Column('etape_courante', sa.SmallInteger(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_souscription_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_souscription')),
    sa.UniqueConstraint('membre_id', name=op.f('uq_souscription_membre_id'))
    )
    op.create_table('visite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_visite_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visite'))
    )
    with op.batch_alter_table('visite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visite_adresse_ip'), ['adresse_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_visite_date_heure'), ['date_heure'], unique=False)

    op.create_table('visite_membre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('date_connexion', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_visite_membre_membre_id_membre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visite_membre'))
    )
    with op.batch_alter_table('visite_membre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visite_membre_membre_id'), ['membre_id'], unique=False)

    op.create_table('appel_fond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('secteur_id', sa.Integer(), nullable=True),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('nom_projet', sa.String(length=150), nullable=False),
    sa.Column('objet_projet', sa.Text(), nullable=False),
    sa.Column('description_activite', sa.Text(), nullable=False),
    sa.Column('description_projet', sa.Text(), nullable=False),
    sa.Column('devis_projet', sa.BigInteger(), nullable=False),
    sa.Column('apport_fond_propre', sa.BigInteger(), nullable=False),
    sa.Column('besoin_financement', sa.BigInteger(), nullable=False),
    sa.Column('niveau_realisation', sa.SmallInteger(), nullable=False),
    sa.Column('nom_promoteur', sa.String(length=120), nullable=False),
    sa.Column('telephone_promoteur', sa.String(length=20), nullable=False),
    sa.Column('email_promoteur', sa.String(length=120), nullable=False),
    sa.Column('adresse_promoteur', sa.Text(), nullable=False),
    sa.Column('observation_gestionnaire', sa.Text(), nullable=False),
    sa.Column('appreciation', sa.SmallInteger(), nullable=False),
    sa.Column('montant_promis', sa.BigInteger(), nullable=False),
    sa.Column('montant_collecte', sa.BigInteger(), nullable=False),
    sa.Column('presentation_pdf', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('date_derniere_visite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['membre.id'], name=op.f('fk_appel_fond_auteur_id_membre')),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('fk_appel_fond_entreprise_id_entreprise')),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur_activite.id'], name=op.f('fk_appel_fond_secteur_id_secteur_activite')),
    sa.ForeignKeyConstraint(['ville_id'], ['ville.id'], name=op.f('fk_appel_fond_ville_id_ville')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appel_fond'))
    )
    with op.batch_alter_table('appel_fond', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appel_fond_reference'), ['reference'], unique=False)

    op.create_table('bench_tarif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('banque_id', sa.Integer(), nullable=False),
    sa.Column('tarif', sa.String(length=100), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['banque_id'], ['banque.id'], name=op.f('fk_bench_tarif_banque_id_banque')),
    sa.ForeignKeyConstraint(['operation_id'], ['bench_operation.id'], name=op.f('fk_bench_tarif_operation_id_bench_operation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bench_tarif'))
    )
    op.create_table('fiche_prospective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('fk_fiche_prospective_entreprise_id_entreprise')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_fiche_prospective_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiche_prospective')),
    sa.UniqueConstraint('entreprise_id', name=op.f('uq_fiche_prospective_entreprise_id'))
    )
    op.create_table('interet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_objet', sa.SmallInteger(), nullable=False),
    sa.Column('sous_type', sa.SmallInteger(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('annonce_emploi_id', sa.Integer(), nullable=True),
    sa.Column('immobilier_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('partenariat_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['annonce_emploi_id'], ['annonce_emploi.id'], name=op.f('fk_interet_annonce_emploi_id_annonce_emploi')),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_interet_article_id_article')),
    sa.ForeignKeyConstraint(['immobilier_id'], ['immobilier.id'], name=op.f('fk_interet_immobilier_id_immobilier')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_interet_membre_id_membre')),
    sa.ForeignKeyConstraint(['partenariat_id'], ['partenariat.id'], name=op.f('fk_interet_partenariat_id_partenariat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interet'))
    )
    with op.batch_alter_table('interet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interet_annonce_emploi_id'), ['annonce_emploi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interet_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interet_immobilier_id'), ['immobilier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interet_partenariat_id'), ['partenariat_id'], unique=False)

    op.create_table('ligne_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('article_catalogue_id', sa.Integer(), nullable=True),
    sa.Column('nom_article', sa.Text(), nullable=False),
    sa.Column('prix_plafond', sa.BigInteger(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_catalogue_id'], ['article_course.id'], name=op.f('fk_ligne_course_article_catalogue_id_article_course')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_ligne_course_course_id_course'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ligne_course'))
    )
    op.create_table('ligne_panier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_objet', sa.SmallInteger(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.BigInteger(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.Column('paye', sa.Boolean(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('paiement_id', sa.Integer(), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_ligne_panier_article_id_article')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_ligne_panier_membre_id_membre')),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiement.id'], name=op.f('fk_ligne_panier_paiement_id_paiement')),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], name=op.f('fk_ligne_panier_produit_id_produit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ligne_panier'))
    )
    with op.batch_alter_table('ligne_panier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ligne_panier_membre_id'), ['membre_id'], unique=False)

    op.create_table('membre_likelemba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('date_entree', sa.Date(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('caution_nom', sa.String(length=120), nullable=False),
    sa.Column('caution_est_membre', sa.SmallInteger(), nullable=False),
    sa.Column('caution_piece_identite', sa.String(length=50), nullable=False),
    sa.Column('caution_adresse', sa.Text(), nullable=False),
    sa.Column('caution_activite', sa.Text(), nullable=False),
    sa.Column('caution_telephone', sa.String(length=20), nullable=False),
    sa.Column('temoins', sa.JSON(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupe_likelemba.id'], name=op.f('fk_membre_likelemba_groupe_id_groupe_likelemba')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_membre_likelemba_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membre_likelemba'))
    )
    with op.batch_alter_table('membre_likelemba', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membre_likelemba_groupe_id'), ['groupe_id'], unique=False)

    op.create_table('operation_banque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_saisie', sa.DateTime(), nullable=False),
    sa.Column('date_operation', sa.Date(), nullable=True),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('devise', sa.SmallInteger(), nullable=False),
    sa.Column('type_operation', sa.SmallInteger(), nullable=False),
    sa.Column('banque_emettrice_id', sa.Integer(), nullable=True),
    sa.Column('banque_emettrice_nom', sa.Text(), nullable=False),
    sa.Column('banque_emettrice_email', sa.Text(), nullable=False),
    sa.Column('beneficiaire', sa.Text(), nullable=False),
    sa.Column('banque_beneficiaire_id', sa.Integer(), nullable=True),
    sa.Column('banque_beneficiaire_nom', sa.Text(), nullable=False),
    sa.Column('banque_beneficiaire_adresse', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['banque_beneficiaire_id'], ['banque.id'], name=op.f('fk_operation_banque_banque_beneficiaire_id_banque')),
    sa.ForeignKeyConstraint(['banque_emettrice_id'], ['banque.id'], name=op.f('fk_operation_banque_banque_emettrice_id_banque')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_operation_banque_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_banque'))
    )
    with op.batch_alter_table('operation_banque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_banque_reference'), ['reference'], unique=False)

    op.create_table('produit_souscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('souscription_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.BigInteger(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], name=op.f('fk_produit_souscription_produit_id_produit')),
    sa.ForeignKeyConstraint(['souscription_id'], ['souscription.id'], name=op.f('fk_produit_souscription_souscription_id_souscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produit_souscription'))
    )
    op.create_table('prospect_souscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('souscription_id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('nom_prenom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_prospect_souscription_membre_id_membre')),
    sa.ForeignKeyConstraint(['souscription_id'], ['souscription.id'], name=op.f('fk_prospect_souscription_souscription_id_souscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prospect_souscription'))
    )
    op.create_table('publicite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('demandeur_id', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('lien', sa.String(length=255), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('type_fichier', sa.SmallInteger(), nullable=False),
    sa.Column('fichier', sa.String(length=255), nullable=True),
    sa.Column('nombre_vues', sa.Integer(), nullable=False),
    sa.Column('date_derniere_vue', sa.DateTime(), nullable=True),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demandeur_id'], ['membre.id'], name=op.f('fk_publicite_demandeur_id_membre')),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name=op.f('fk_publicite_entreprise_id_entreprise')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publicite'))
    )
    op.create_table('collecte_fond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('appel_fond_id', sa.Integer(), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=True),
    sa.Column('date_engagement', sa.Date(), nullable=True),
    sa.Column('type_apport', sa.SmallInteger(), nullable=False),
    sa.Column('montant_promis', sa.BigInteger(), nullable=False),
    sa.Column('echeance_mois', sa.SmallInteger(), nullable=False),
    sa.Column('montant_verse', sa.BigInteger(), nullable=False),
    sa.Column('date_dernier_versement', sa.Date(), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=False),
    sa.Column('observation_mediateur', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['appel_fond_id'], ['appel_fond.id'], name=op.f('fk_collecte_fond_appel_fond_id_appel_fond')),
    sa.ForeignKeyConstraint(['membre_id'], ['membre.id'], name=op.f('fk_collecte_fond_membre_id_membre')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collecte_fond'))
    )
    with op.batch_alter_table('collecte_fond', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collecte_fond_appel_fond_id'), ['appel_fond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collecte_fond_reference'), ['reference'], unique=False)

    op.create_table('cotisation_likelemba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.Column('adhesion_id', sa.Integer(), nullable=True),
    sa.Column('caissier_id', sa.Integer(), nullable=True),
    sa.Column('numero_recu', sa.String(length=30), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('mode_paiement', sa.SmallInteger(), nullable=False),
    sa.Column('code_transfert', sa.String(length=30), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.Column('paiement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adhesion_id'], ['membre_likelemba.id'], name=op.f('fk_cotisation_likelemba_adhesion_id_membre_likelemba')),
    sa.ForeignKeyConstraint(['caissier_id'], ['membre.id'], name=op.f('fk_cotisation_likelemba_caissier_id_membre')),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupe_likelemba.id'], name=op.f('fk_cotisation_likelemba_groupe_id_groupe_likelemba')),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiement.id'], name=op.f('fk_cotisation_likelemba_paiement_id_paiement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cotisation_likelemba'))
    )
    with op.batch_alter_table('cotisation_likelemba', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotisation_likelemba_groupe_id'), ['groupe_id'], unique=False)

    op.create_table('ligne_prospective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('offre_ou_demande', sa.SmallInteger(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('unite_vente', sa.String(length=50), nullable=False),
    sa.Column('prix', sa.BigInteger(), nullable=False),
    sa.Column('fournisseur_ou_client', sa.Text(), nullable=False),
    sa.Column('quantite_mensuelle', sa.Integer(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiche_prospective.id'], name=op.f('fk_ligne_prospective_fiche_id_fiche_prospective'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produit_prospective.id'], name=op.f('fk_ligne_prospective_produit_id_produit_prospective')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ligne_prospective'))
    )
    with op.batch_alter_table('ligne_prospective', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ligne_prospective_produit_id'), ['produit_id'], unique=False)

    op.create_table('versement_collecte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collecte_id', sa.Integer(), nullable=False),
    sa.Column('date_versement', sa.Date(), nullable=False),
    sa.Column('montant', sa.BigInteger(), nullable=False),
    sa.Column('etat', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['collecte_id'], ['collecte_fond.id'], name=op.f('fk_versement_collecte_collecte_id_collecte_fond')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versement_collecte'))
    )
    with op.batch_alter_table('versement_collecte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versement_collecte_collecte_id'), ['collecte_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versement_collecte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versement_collecte_collecte_id'))

    op.drop_table('versement_collecte')
    with op.batch_alter_table('ligne_prospective', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligne_prospective_produit_id'))

    op.drop_table('ligne_prospective')
    with op.batch_alter_table('cotisation_likelemba', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotisation_likelemba_groupe_id'))

    op.drop_table('cotisation_likelemba')
    with op.batch_alter_table('collecte_fond', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collecte_fond_reference'))
        batch_op.drop_index(batch_op.f('ix_collecte_fond_appel_fond_id'))

    op.drop_table('collecte_fond')
    op.drop_table('publicite')
    op.drop_table('prospect_souscription')
    op.drop_table('produit_souscription')
    with op.batch_alter_table('operation_banque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_banque_reference'))

    op.drop_table('operation_banque')
    with op.batch_alter_table('membre_likelemba', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membre_likelemba_groupe_id'))

    op.drop_table('membre_likelemba')
    with op.batch_alter_table('ligne_panier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligne_panier_membre_id'))

    op.drop_table('ligne_panier')
    op.drop_table('ligne_course')
    with op.batch_alter_table('interet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interet_partenariat_id'))
        batch_op.drop_index(batch_op.f('ix_interet_immobilier_id'))
        batch_op.drop_index(batch_op.f('ix_interet_article_id'))
        batch_op.drop_index(batch_op.f('ix_interet_annonce_emploi_id'))

    op.drop_table('interet')
    op.drop_table('fiche_prospective')
    op.drop_table('bench_tarif')
    with op.batch_alter_table('appel_fond', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appel_fond_reference'))

    op.drop_table('appel_fond')
    with op.batch_alter_table('visite_membre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visite_membre_membre_id'))

    op.drop_table('visite_membre')
    with op.batch_alter_table('visite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visite_date_heure'))
        batch_op.drop_index(batch_op.f('ix_visite_adresse_ip'))

    op.drop_table('visite')
    op.drop_table('souscription')
    op.drop_table('soungangai')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_membre_id'))

    op.drop_table('session')
    op.drop_table('reussite')
    op.drop_table('reinitialisation_mot_de_passe')
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projet_reference'))

    op.drop_table('projet')
    with op.batch_alter_table('point_caisse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_caisse_reference'))
        batch_op.drop_index(batch_op.f('ix_point_caisse_membre_id'))
        batch_op.drop_index(batch_op.f('ix_point_caisse_date_heure'))

    op.drop_table('point_caisse')
    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_reference'))

    op.drop_table('placement')
    with op.batch_alter_table('partenariat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partenariat_reference'))

    op.drop_table('partenariat')
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paiement_membre_id'))
        batch_op.drop_index(batch_op.f('ix_paiement_etat'))

    op.drop_table('paiement')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_membre_id'))

    op.drop_table('message')
    with op.batch_alter_table('marche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marche_reference'))

    op.drop_table('marche')
    with op.batch_alter_table('immobilier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immobilier_reference'))
        batch_op.drop_index(batch_op.f('ix_immobilier_offre_ou_recherche'))

    op.drop_table('immobilier')
    with op.batch_alter_table('groupe_likelemba', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groupe_likelemba_code'))

    op.drop_table('groupe_likelemba')
    with op.batch_alter_table('fond_de_soutien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fond_de_soutien_reference'))

    op.drop_table('fond_de_soutien')
    with op.batch_alter_table('entreprise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entreprise_reference'))

    op.drop_table('entreprise')
    with op.batch_alter_table('dossier_accompagnement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_accompagnement_type_dossier'))
        batch_op.drop_index(batch_op.f('ix_dossier_accompagnement_reference'))

    op.drop_table('dossier_accompagnement')
    with op.batch_alter_table('dialogue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialogue_type_dialogue'))

    op.drop_table('dialogue')
    with op.batch_alter_table('demande_credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demande_credit_reference'))

    op.drop_table('demande_credit')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_reference'))
        batch_op.drop_index(batch_op.f('ix_course_client_id'))

    op.drop_table('course')
    with op.batch_alter_table('contentieux_credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contentieux_credit_reference'))

    op.drop_table('contentieux_credit')
    op.drop_table('contact')
    with op.batch_alter_table('conseil_finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conseil_finance_sujet_id'))
        batch_op.drop_index(batch_op.f('ix_conseil_finance_rubrique'))
        batch_op.drop_index(batch_op.f('ix_conseil_finance_reference'))

    op.drop_table('conseil_finance')
    with op.batch_alter_table('conseil', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conseil_sujet_id'))
        batch_op.drop_index(batch_op.f('ix_conseil_reference'))

    op.drop_table('conseil')
    op.drop_table('business_plan')
    op.drop_table('banque')
    with op.batch_alter_table('article_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_course_boutique_id'))

    op.drop_table('article_course')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_reference'))
        batch_op.drop_index(batch_op.f('ix_article_offre_ou_recherche'))

    op.drop_table('article')
    with op.batch_alter_table('annonce_emploi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annonce_emploi_type_annonce'))
        batch_op.drop_index(batch_op.f('ix_annonce_emploi_reference'))

    op.drop_table('annonce_emploi')
    with op.batch_alter_table('membre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membre_telephone'))
        batch_op.drop_index(batch_op.f('ix_membre_email'))

    op.drop_table('membre')
    op.drop_table('quartier')
    op.drop_table('maladie_produit')
    op.drop_table('domaine_activite')
    op.drop_table('bench_operation')
    op.drop_table('ville')
    with op.batch_alter_table('tentative_connexion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tentative_connexion_date_heure'))
        batch_op.drop_index(batch_op.f('ix_tentative_connexion_cle'))

    op.drop_table('tentative_connexion')
    op.drop_table('suggestion')
    op.drop_table('secteur_activite')
    op.drop_table('produit_prospective')
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produit_groupe'))

    op.drop_table('produit')
    op.drop_table('parametre')
    op.drop_table('maladie')
    op.drop_table('famille_article')
    op.drop_table('diplome')
    op.drop_table('bench_type')
    # ### end Alembic commands ###
